# Generated by Django 4.1.1 on 2022-09-26 05:49

import Status_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Status_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Status_App.models.upload_status_image),
        ),
    ]
